# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yuchen Liu
description: >- # this means to ignore newlines until "baseurl:"
  Hi! My name is Yuchen Liu. I'm a Ph.D. student majoring in astronomy.
baseurl: ""
url: "https://yuchenliu-astro.github.io" # the base hostname & protocol for the site
og_image: /assets/img/myphoto.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: CV
    - name: Publication
    - name: More

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: yuchen.liu@stu.pku.edu.cn

  follow:
    - type: googlescholar
      name: G-Scholar
      link: https://scholar.google.com/citations?user=OqBD2X4AAAAJ&hl=en
      username: "@YourTwitterUsername"
    - type: orcid
      name: ORCID
      link: https://orcid.org/0009-0008-6770-3583
    - type: github
      name: GitHub
      link: http://github.com/yuchenliu-astro


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - build/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - tasks/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
